# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 02:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('H', 'History'), ('G', 'Geography'), ('SC', 'Science'), ('SP', 'Sports'), ('A', 'Art'), ('E', 'Entertainment')], default='E', max_length=2)),
                ('dificulty', models.CharField(choices=[('E', 'Easy'), ('N', 'Normal'), ('H', 'Hard')], default='N', max_length=1)),
                ('correctop', models.IntegerField(default=1)),
                ('time', models.IntegerField(default=30)),
                ('reward', models.IntegerField(default=100)),
                ('cost', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preguntas.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preguntas.Question'),
        ),
    ]
