# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 02:36
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('age', models.CharField(blank=True, max_length=30, null=True)),
                ('hobbies', models.CharField(blank=True, max_length=30, null=True)),
                ('favcategory', multiselectfield.db.fields.MultiSelectField(choices=[('H', 'History'), ('G', 'Geography'), ('SC', 'Science'), ('SP', 'Sports'), ('A', 'Art'), ('E', 'Entertainment')], max_length=13)),
                ('picture', models.ImageField(blank=True, upload_to=b'')),
                ('coins', models.IntegerField(default=100)),
                ('daily', models.BooleanField(default=False)),
                ('newquestions', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
